### ISSUE TITLE
License and copyright

### ISSUE THREAD

**Issue by lassik** [dylan-lang/dylan-emacs-support#52]
Files with Dime prefix

* `dime-browse.el` -- good authorship info, GPL version 2 or later.
* `dime-note-tree.el` -- who wrote this? GPL version 2 or later.
* `dime-repl.el` -- file says main author is Helmut Eller, GPL version 2 or later.
* `dime.el` -- file lists several authors, GPL version 2 or later.
 
Files with Dylan prefix

* `dylan-lid.el` -- file says it's written by Erik Charlebois, GPL version 1 or later.
* `dylan-mode.el` -- good authorship info, GPL version 1 or later.
* `dylan-optimization-coloring.el` -- no license info at all, git log shows it's mainly Hannes Mehnert's work.

**Comment by cgay** [comment]
@hannesm can you comment?

**Comment by hannesm** [comment]
I do not remember the exact circumstances (git log / blame should be able to discover where the files originate from). I'm fine with any license (being it ISC/BSD or GPL) for the code I wrote, whatever is preferable to have a single license in this repository.

**Comment by lassik** [comment]
If we desire a common license for all this code, `GPL-2.0-or-later` would be the simplest choice. To the extent that we know the current licenses, we have some GPLv1 code, some GPLv2 code, and no GPLv3 code.

**Comment by lassik** [comment]
The Dylan compiler seems to use a MIT/BSD style permissive license. Like Hannes, I'm also fine with a permissive license for any code I write. However, it may be hard to track down all the others, so sticking with GPL would be simplest.

**Comment by cgay** [comment]
I prefer MIT in general but have no problem with GPL2 for the elisp code if it's simpler.

**Comment by lassik** [comment]
All the files now have `SPDX-License-Identifier:` saying GPL, and there's a copy of GPL 2 in the `LICENSE` file.
