### ISSUE TITLE
Splitting the MELPA package into two packages

### ISSUE THREAD

**Issue by lassik** [dylan-lang/dylan-emacs-support#53]
Currently we have two sets of files: `dylan-*.el` and `dime-*.el`. There seems to be a somewhat clean separation between Dime and the other Dylan stuff. The Dime stuff depends on the Dylan stuff, but the Dylan stuff can also be used standalone.

In light of this division, I think we should split into two different Melpa packages: `dylan` and `dime`, with `dylan` as a dependency for `dime`. Both package names are available so there is no conflict with existing packages.

We can still keep both packages in the same git repo. A Melpa recipe can be written to only pick files matching a shell glob from a repo.

**Comment by pedro-w** [comment]
I see that would work, but is there a benefit to doing it?

**Comment by lassik** [comment]
The filename and symbol prefixes would match the package name, which is the usual convention. The `dylan-mode` package was added to Melpa early, back when they didn't yet do much in the way of code review, so it doesn't currently observe this convention.

**Comment by lassik** [comment]
I continue to advocate for the `dylan`/`dime` split as per MELPA conventions. Since most of our work is done, now would be a good time to send the requisite PRs to them.

**Comment by lassik** [comment]
@housel Any opinion on the MELPA package splitting and repo renaming?

**Comment by housel** [comment]
Sure, I'm fine with that.

**Comment by lassik** [comment]
@cgay Can you rename the repo? I can send the pull request to MELPA.

**Comment by cgay** [comment]
Done. I went with `dylan-emacs-support`.

**Comment by lassik** [comment]
This is now done, `dylan` and `dime` packages are up on MELPA. Please try uninstalling `dylan-mode`, installing the new packages, and open new issues for any problems you encounter (we made a lot of changes so there are sure to be a few).

**Comment by lassik** [comment]
For reference, the PR was https://github.com/melpa/melpa/pull/7483
